#!/bin/bash

while true
do

	ping -c 2 -q -w 5 8.8.8.8 > /dev/null 2>&1

	if ! [ "$?" = 0 ] ;
	then
 		log="Ping 1 falhou em $(date +%d/%m/%Y) às $(date +%T)"
		sleep 60
		ping -c 2 -q -w 5 8.8.4.4 > /dev/null 2>&1	
		if ! [ "$?" = 0 ] ;
		then
			log+="\nPing 2 falhou em $(date +%d/%m/%Y) às $(date +%T)"
		fi	
		echo -e "$log\n---------------------------------------" >> ~/.netLog
	fi
	sleep 300
done
