#!/bin/bash

arquivoConfig=~/.gitconfig

repositorio=$1
ramo=$2

if ! [ -e "$arquivoConfig" ]; then
	echo "Digite seu nome"
	read nome
	echo "Digite seu e-mail"
	read email
	git config --global user.name "$nome"
	git config --global user.email "$email"
fi

if [ "${1}" = "-m" ];then
	echo "Digite comentário para commit"
	read textoCommit
else
	repositorio=$2
	ramo=$3	
    textoCommit="Atualizado em $(date +%d/%m/%Y) às $(date +%T)"
fi

if  [ -z "${2}" ]; then
    repositorio="origin"
fi

if [ -z "${3}" ]; then
    ramo="master"
fi

git add . 
git commit -m "$textoCommit"
git push $repositorio $ramo 


